# Generated by Django 6.1 on 2026-08-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Site",
            new_name="Company",
        ),
        migrations.RemoveIndex(
            model_name="jobposting",
            name="app_jobpost_source__5680fa_idx",
        ),
        migrations.RenameField(
            model_name="jobposting",
            old_name="source_site",
            new_name="source_company",
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["source_company", "scraped_at"],
                name="app_jobpost_source__60dec2_idx",
            ),
        ),
    ]
