# Generated by Django 6.1 on 2026-08-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                ("frequency", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "wait_selector",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=64)),
                ("source_url", models.URLField(max_length=500)),
                ("scraped_at", models.DateTimeField()),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("location", models.CharField(blank=True, max_length=300, null=True)),
                ("department", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "employment_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "posted_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("salary_min", models.FloatField(blank=True, null=True)),
                ("salary_max", models.FloatField(blank=True, null=True)),
                (
                    "salary_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("salary_raw", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "source_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="app.site",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_site", "scraped_at"],
                        name="app_jobpost_source__5680fa_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_id", "scraped_at"), name="unique_job_per_run"
                    )
                ],
            },
        ),
    ]
