# Generated by Django 6.1 on 2026-08-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_site_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="wait_selector",
        ),
    ]
