# Generated by Django 6.1 on 2026-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_company_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
