# Generated by Django 6.1 on 2026-08-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_userpreferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="salary_raw",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="description",
        ),
    ]
