# Generated by Django 6.1 on 2026-08-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_job_lifetime_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="last_content_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
