# Generated by Django 6.1 on 2026-08-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_company_last_content_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="source_url",
        ),
    ]
